import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

enum ToolCategory {
  pdfTools,
  imageTools,
  calculatorTools,
  otherTools,
}

enum ProcessingMode {
  local, // On-device processing
  api, // Backend API processing
}

enum ToolPriority {
  p0, // MVP
  p1, // Version 1.1
  p2, // Version 1.2+
}

extension ToolCategoryExtension on ToolCategory {
  String get displayName {
    switch (this) {
      case ToolCategory.pdfTools:
        return 'PDF Tools';
      case ToolCategory.imageTools:
        return 'Image Tools';
      case ToolCategory.calculatorTools:
        return 'Calculators';
      case ToolCategory.otherTools:
        return 'Other Tools';
    }
  }

  Color get color {
    switch (this) {
      case ToolCategory.pdfTools:
        return AppColors.pdfCategory;
      case ToolCategory.imageTools:
        return AppColors.imageCategory;
      case ToolCategory.calculatorTools:
        return AppColors.calculatorCategory;
      case ToolCategory.otherTools:
        return AppColors.otherCategory;
    }
  }

  IconData get icon {
    switch (this) {
      case ToolCategory.pdfTools:
        return Icons.picture_as_pdf;
      case ToolCategory.imageTools:
        return Icons.image;
      case ToolCategory.calculatorTools:
        return Icons.calculate;
      case ToolCategory.otherTools:
        return Icons.build;
    }
  }
}

class AppTool {
  final String id;
  final String name;
  final String description;
  final String shortDescription;
  final ToolCategory category;
  final ProcessingMode processingMode;
  final ToolPriority priority;
  final IconData icon;
  final List<String> supportedInputFormats;
  final List<String> supportedOutputFormats;
  final List<String> instructions;
  final List<String> features;
  final bool supportsMultipleFiles;
  final int maxFileSizeMB;
  final int maxFilesCount;

  const AppTool({
    required this.id,
    required this.name,
    required this.description,
    required this.shortDescription,
    required this.category,
    required this.processingMode,
    required this.priority,
    required this.icon,
    required this.supportedInputFormats,
    required this.supportedOutputFormats,
    required this.instructions,
    this.features = const [],
    this.supportsMultipleFiles = false,
    this.maxFileSizeMB = 25,
    this.maxFilesCount = 5,
  });
}

// All P0 (MVP) Tools from PRD
final List<AppTool> allTools = [
  // ==================== PDF TOOLS (P0) ====================
  const AppTool(
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    shortDescription: 'Merge PDFs',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.merge_type,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    supportsMultipleFiles: true,
    maxFilesCount: 10,
    instructions: [
      'Select 2 or more PDF files',
      'Arrange files in desired order',
      'Tap Merge PDFs to combine',
      'Download your merged PDF',
    ],
    features: [
      'Drag to reorder files',
      'No file size limit for browser processing',
      'Preserves all PDF content',
    ],
  ),
  const AppTool(
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Split PDF by page ranges or extract individual pages',
    shortDescription: 'Split PDFs',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.call_split,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf', 'zip'],
    instructions: [
      'Select a PDF file',
      'Choose split mode (range, extract, or all pages)',
      'Specify page numbers or ranges',
      'Download split files',
    ],
    features: [
      'Split by page range',
      'Extract single pages',
      'Download as ZIP',
    ],
  ),
  const AppTool(
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    shortDescription: 'Compress PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.compress,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select a PDF file',
      'Choose compression level',
      'Tap Compress PDF',
      'Download compressed file',
    ],
    features: [
      'Low, Medium, High compression levels',
      'See before/after file size',
      'Preserve text quality',
    ],
  ),
  const AppTool(
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files to editable Word documents',
    shortDescription: 'PDF to DOCX',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.description,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['docx'],
    instructions: [
      'Select a PDF file',
      'Tap Convert to Word',
      'Wait for processing',
      'Download DOCX file',
    ],
    features: [
      'Preserves formatting',
      'Editable text output',
      'Fast conversion',
    ],
  ),
  const AppTool(
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables to Excel spreadsheets',
    shortDescription: 'PDF to XLSX',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.table_chart,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['xlsx'],
    instructions: [
      'Select a PDF with tables',
      'Tap Convert to Excel',
      'Wait for processing',
      'Download XLSX file',
    ],
    features: [
      'Table recognition',
      'Preserves formatting',
      'Editable spreadsheets',
    ],
  ),
  const AppTool(
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    shortDescription: 'DOCX to PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.picture_as_pdf,
    supportedInputFormats: ['docx', 'doc'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select a Word file',
      'Tap Convert to PDF',
      'Wait for processing',
      'Download PDF file',
    ],
    features: [
      'Preserves formatting',
      'Universal PDF output',
      'Fast conversion',
    ],
  ),
  const AppTool(
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF documents',
    shortDescription: 'JPG to PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.image,
    supportedInputFormats: ['jpg', 'jpeg'],
    supportedOutputFormats: ['pdf'],
    supportsMultipleFiles: true,
    maxFilesCount: 20,
    instructions: [
      'Select JPG images',
      'Set page orientation and margins',
      'Tap Convert to PDF',
      'Download PDF file',
    ],
    features: [
      'Portrait/Landscape options',
      'Custom margins',
      'Multiple images support',
    ],
  ),
  const AppTool(
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert any image format to PDF',
    shortDescription: 'Images to PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.photo_library,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif'],
    supportedOutputFormats: ['pdf'],
    supportsMultipleFiles: true,
    maxFilesCount: 20,
    instructions: [
      'Select images from gallery',
      'Arrange images in order',
      'Set orientation and margins',
      'Download PDF file',
    ],
    features: [
      'Multiple image formats',
      'Drag to reorder',
      'Custom page settings',
    ],
  ),
  const AppTool(
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    shortDescription: 'PDF to JPG',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.image,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['jpg', 'zip'],
    instructions: [
      'Select a PDF file',
      'Choose pages to convert',
      'Tap Convert to JPG',
      'Download images',
    ],
    features: [
      'Convert all or selected pages',
      'High quality output',
      'ZIP download option',
    ],
  ),
  const AppTool(
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF to PNG, WebP, or other image formats',
    shortDescription: 'PDF to Images',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.image_outlined,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['png', 'webp', 'jpg', 'zip'],
    instructions: [
      'Select a PDF file',
      'Choose output format',
      'Tap Convert to Image',
      'Download images',
    ],
    features: [
      'Multiple output formats',
      'Page selection',
      'Batch conversion',
    ],
  ),

  // ==================== IMAGE TOOLS (P0) ====================
  const AppTool(
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce image file size while maintaining quality',
    shortDescription: 'Compress Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.compress,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    instructions: [
      'Select an image',
      'Set target quality or size',
      'Tap Compress',
      'Download compressed image',
    ],
    features: [
      'Quality control slider',
      'See before/after size',
      'No upload required',
    ],
  ),
  const AppTool(
    id: 'compress-to-100kb',
    name: 'Compress to 100KB',
    description: 'Compress any image to exactly 100KB',
    shortDescription: '100KB Compress',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.photo_size_select_small,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp'],
    supportedOutputFormats: ['jpg'],
    instructions: [
      'Select an image',
      'Tap Compress to 100KB',
      'Auto-adjusts quality',
      'Download compressed image',
    ],
    features: [
      'Perfect for forms',
      'Automatic optimization',
      'One-click operation',
    ],
  ),
  const AppTool(
    id: 'compress-to-20kb',
    name: 'Compress to 20KB',
    description: 'Compress images to exactly 20KB for government forms',
    shortDescription: '20KB Compress',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.photo_size_select_small,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg'],
    instructions: [
      'Select an image',
      'Tap Compress to 20KB',
      'Auto-adjusts quality',
      'Download compressed image',
    ],
    features: [
      'Perfect for passport photos',
      'Government form compliant',
      'Automatic optimization',
    ],
  ),
  const AppTool(
    id: 'crop-image',
    name: 'Crop Image',
    description: 'Crop images with custom dimensions or presets',
    shortDescription: 'Crop Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.crop,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    instructions: [
      'Select an image',
      'Choose crop preset or freehand',
      'Adjust crop area',
      'Download cropped image',
    ],
    features: [
      'Passport size preset (35x45mm)',
      'Social media presets',
      'Freehand cropping',
    ],
  ),
  const AppTool(
    id: 'resize-image',
    name: 'Resize Image',
    description: 'Resize images by pixels or percentage',
    shortDescription: 'Resize Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.photo_size_select_large,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    instructions: [
      'Select an image',
      'Enter new dimensions or percentage',
      'Lock aspect ratio (optional)',
      'Download resized image',
    ],
    features: [
      'Pixel or percentage resize',
      'Aspect ratio lock',
      'Multiple formats',
    ],
  ),
  const AppTool(
    id: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate images 90°, 180°, or 270°',
    shortDescription: 'Rotate Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.rotate_right,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    instructions: [
      'Select an image',
      'Choose rotation angle',
      'Tap Rotate',
      'Download rotated image',
    ],
    features: [
      '90°, 180°, 270° rotation',
      'Flip horizontal/vertical',
      'Instant processing',
    ],
  ),
  const AppTool(
    id: 'convert-to-jpg',
    name: 'Convert to JPG',
    description: 'Convert any image to JPG format',
    shortDescription: 'To JPG',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.image,
    supportedInputFormats: ['png', 'webp', 'bmp', 'gif', 'tiff'],
    supportedOutputFormats: ['jpg', 'jpeg'],
    instructions: [
      'Select an image',
      'Set JPG quality (optional)',
      'Tap Convert',
      'Download JPG file',
    ],
    features: [
      'Quality control',
      'Universal compatibility',
      'Smaller file sizes',
    ],
  ),
  const AppTool(
    id: 'convert-from-jpg',
    name: 'Convert from JPG',
    description: 'Convert JPG to PNG, WebP, or other formats',
    shortDescription: 'From JPG',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.image_outlined,
    supportedInputFormats: ['jpg', 'jpeg'],
    supportedOutputFormats: ['png', 'webp', 'bmp'],
    instructions: [
      'Select a JPG image',
      'Choose output format',
      'Tap Convert',
      'Download converted image',
    ],
    features: [
      'PNG for transparency',
      'WebP for smaller sizes',
      'Lossless conversion',
    ],
  ),

  // ==================== CALCULATOR TOOLS (P0) ====================
  const AppTool(
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate exact age from birth date to today or any date',
    shortDescription: 'Age Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.cake,
    supportedInputFormats: ['date'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter your birth date',
      'Select end date (today or custom)',
      'View age in years, months, days',
      'Copy results to clipboard',
    ],
    features: [
      'Years, months, days breakdown',
      'Next birthday countdown',
      'Calculate to any date',
    ],
  ),
  const AppTool(
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Find percentage of any number with ease',
    shortDescription: 'Percentage Calc',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.percent,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter the base value',
      'Enter the percentage',
      'Get instant result',
      'Copy calculation',
    ],
    features: [
      'Find X% of Y',
      'Percentage increase/decrease',
      'Reverse percentage',
    ],
  ),
  const AppTool(
    id: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Calculate GST inclusive and exclusive prices',
    shortDescription: 'GST Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.receipt,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter base amount',
      'Select GST rate (5%, 12%, 18%, 28%)',
      'Choose inclusive or exclusive',
      'View detailed breakdown',
    ],
    features: [
      'All GST slabs (5%, 12%, 18%, 28%)',
      'Add or remove GST',
      'CGST/SGST split',
    ],
  ),
  const AppTool(
    id: 'emi-calculator',
    name: 'EMI Calculator',
    description: 'Calculate loan EMI and repayment schedule',
    shortDescription: 'EMI Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.account_balance,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter loan amount',
      'Set interest rate',
      'Set loan tenure in years/months',
      'View EMI and total interest',
    ],
    features: [
      'Monthly EMI amount',
      'Total interest payable',
      'Amortization schedule',
    ],
  ),
  const AppTool(
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index with healthy range',
    shortDescription: 'BMI Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.monitor_weight,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter height (cm or feet/inches)',
      'Enter weight (kg or lbs)',
      'Get BMI value instantly',
      'See weight category',
    ],
    features: [
      'Metric and Imperial units',
      'Weight category indicator',
      'Ideal weight range',
    ],
  ),
  const AppTool(
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate days between two dates',
    shortDescription: 'Date Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.date_range,
    supportedInputFormats: ['date'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Select start date',
      'Select end date',
      'View days difference',
      'Add/subtract days from date',
    ],
    features: [
      'Days between dates',
      'Add/subtract days',
      'Weekdays calculation',
    ],
  ),
  const AppTool(
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between major world currencies',
    shortDescription: 'Currency Convert',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.currency_exchange,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter amount',
      'Select source currency',
      'Select target currency',
      'View converted amount',
    ],
    features: [
      '50+ currencies supported',
      'Live exchange rates',
      'Quick currency swap',
    ],
  ),

  // ==================== OTHER TOOLS (P0) ====================
  const AppTool(
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for text, URLs, or contact info',
    shortDescription: 'QR Generator',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.qr_code,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['png', 'svg'],
    instructions: [
      'Enter text or URL',
      'Customize colors (optional)',
      'Set QR code size',
      'Download QR code',
    ],
    features: [
      'Custom colors',
      'Multiple sizes',
      'PNG & SVG export',
    ],
  ),

  // ==================== MORE CALCULATORS (P0) ====================
  const AppTool(
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Calculate compound interest with different frequencies',
    shortDescription: 'Compound Interest',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.trending_up,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter principal amount',
      'Set annual interest rate',
      'Choose compounding frequency',
      'Set time period',
    ],
    features: [
      'Monthly, quarterly, yearly compounding',
      'Total interest earned',
      'Final maturity amount',
    ],
  ),
  const AppTool(
    id: 'simple-interest',
    name: 'Simple Interest',
    description: 'Calculate simple interest quickly',
    shortDescription: 'Simple Interest',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.calculate_outlined,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter principal amount',
      'Set interest rate',
      'Set time period',
      'Get simple interest',
    ],
    features: [
      'Quick calculation',
      'Total amount with interest',
      'Multiple time units',
    ],
  ),
  const AppTool(
    id: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate restaurant tips and split bills',
    shortDescription: 'Tip Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.restaurant,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter bill amount',
      'Set tip percentage',
      'Split among people',
      'View per person amount',
    ],
    features: [
      'Custom tip percentages',
      'Split bill calculator',
      'Round up option',
    ],
  ),
  const AppTool(
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between various units of measurement',
    shortDescription: 'Unit Converter',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.swap_horiz,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Select unit category',
      'Enter value',
      'Choose source and target units',
      'See conversion result',
    ],
    features: [
      'Length, Weight, Temperature',
      'Volume, Area, Speed',
      'Instant conversion',
    ],
  ),
  const AppTool(
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Advanced calculator with scientific functions',
    shortDescription: 'Scientific Calc',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.functions,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter mathematical expression',
      'Use scientific functions',
      'View result',
      'Copy calculation',
    ],
    features: [
      'Trigonometric functions',
      'Logarithms, powers, roots',
      'History of calculations',
    ],
  ),
  const AppTool(
    id: 'fd-calculator',
    name: 'FD Calculator',
    description: 'Fixed Deposit maturity and interest calculator',
    shortDescription: 'FD Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.account_balance_wallet,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter deposit amount',
      'Set interest rate',
      'Choose tenure',
      'View maturity amount',
    ],
    features: [
      'Maturity value calculation',
      'Interest earned',
      'Senior citizen rates',
    ],
  ),
  const AppTool(
    id: 'rd-calculator',
    name: 'RD Calculator',
    description: 'Recurring Deposit calculator',
    shortDescription: 'RD Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.savings,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter monthly deposit',
      'Set interest rate',
      'Choose tenure in months',
      'View maturity amount',
    ],
    features: [
      'Monthly installment planning',
      'Maturity value',
      'Total interest earned',
    ],
  ),
  const AppTool(
    id: 'ppf-calculator',
    name: 'PPF Calculator',
    description: 'Public Provident Fund calculator for India',
    shortDescription: 'PPF Calculator',
    category: ToolCategory.calculatorTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.school,
    supportedInputFormats: ['number'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter yearly investment',
      'Current PPF rate auto-filled',
      'Set investment period',
      'View maturity amount',
    ],
    features: [
      'Tax-free returns',
      '15-year maturity',
      'Loan and withdrawal options',
    ],
  ),

  // ==================== MORE IMAGE TOOLS (P0) ====================
  const AppTool(
    id: 'flip-image',
    name: 'Flip Image',
    description: 'Flip images horizontally or vertically',
    shortDescription: 'Flip Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.flip,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    instructions: [
      'Select an image',
      'Choose flip direction',
      'Tap Flip',
      'Download flipped image',
    ],
    features: [
      'Horizontal flip',
      'Vertical flip',
      'Instant preview',
    ],
  ),
  const AppTool(
    id: 'remove-bg',
    name: 'Remove Background',
    description: 'Remove image background automatically',
    shortDescription: 'Remove BG',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.auto_fix_high,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['png'],
    instructions: [
      'Select an image',
      'Tap Remove Background',
      'Wait for AI processing',
      'Download transparent PNG',
    ],
    features: [
      'AI-powered removal',
      'Transparent output',
      'Perfect for product photos',
    ],
  ),
  const AppTool(
    id: 'blur-image',
    name: 'Blur Image',
    description: 'Add blur effect to images',
    shortDescription: 'Blur Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.blur_on,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png'],
    instructions: [
      'Select an image',
      'Adjust blur intensity',
      'Apply blur',
      'Download image',
    ],
    features: [
      'Gaussian blur',
      'Adjustable intensity',
      'Background blur option',
    ],
  ),
  const AppTool(
    id: 'sharpen-image',
    name: 'Sharpen Image',
    description: 'Enhance image sharpness and clarity',
    shortDescription: 'Sharpen Image',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.auto_awesome,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png'],
    instructions: [
      'Select an image',
      'Adjust sharpness level',
      'Apply enhancement',
      'Download sharpened image',
    ],
    features: [
      'Unsharp mask filter',
      'Clarity enhancement',
      'Detail preservation',
    ],
  ),
  const AppTool(
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Add text or image watermarks to photos',
    shortDescription: 'Watermark',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.water_drop,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png'],
    instructions: [
      'Select an image',
      'Enter watermark text',
      'Customize position and opacity',
      'Download watermarked image',
    ],
    features: [
      'Text and image watermarks',
      'Position and size control',
      'Opacity adjustment',
    ],
  ),
  const AppTool(
    id: 'grayscale',
    name: 'Grayscale Image',
    description: 'Convert images to black and white',
    shortDescription: 'Grayscale',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.filter_b_and_w,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png'],
    instructions: [
      'Select an image',
      'Tap Convert to Grayscale',
      'Preview result',
      'Download B&W image',
    ],
    features: [
      'True grayscale conversion',
      'Preserves contrast',
      'Instant processing',
    ],
  ),
  const AppTool(
    id: 'sepia-image',
    name: 'Sepia Filter',
    description: 'Apply vintage sepia tone to images',
    shortDescription: 'Sepia Filter',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.filter_vintage,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg', 'jpeg', 'png'],
    instructions: [
      'Select an image',
      'Apply Sepia filter',
      'Adjust intensity',
      'Download vintage image',
    ],
    features: [
      'Classic sepia tone',
      'Adjustable warmth',
      'Vintage photo effect',
    ],
  ),
  const AppTool(
    id: 'compress-to-50kb',
    name: 'Compress to 50KB',
    description: 'Compress images to exactly 50KB',
    shortDescription: '50KB Compress',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.photo_size_select_small,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    supportedOutputFormats: ['jpg'],
    instructions: [
      'Select an image',
      'Tap Compress to 50KB',
      'Auto-adjusts quality',
      'Download compressed image',
    ],
    features: [
      'Exact 50KB output',
      'Perfect for forms',
      'Automatic optimization',
    ],
  ),

  // ==================== MORE PDF TOOLS (P0) ====================
  const AppTool(
    id: 'extract-pdf-pages',
    name: 'Extract PDF Pages',
    description: 'Extract specific pages from a PDF',
    shortDescription: 'Extract Pages',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.content_cut,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select a PDF file',
      'Choose pages to extract',
      'Tap Extract',
      'Download new PDF',
    ],
    features: [
      'Extract single or range',
      'Custom page selection',
      'Preserves formatting',
    ],
  ),
  const AppTool(
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract plain text from PDF files',
    shortDescription: 'PDF to Text',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.text_snippet,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['txt'],
    instructions: [
      'Select a PDF file',
      'Tap Extract Text',
      'Wait for processing',
      'Download text file',
    ],
    features: [
      'Preserves text layout',
      'Editable output',
      'No formatting loss',
    ],
  ),
  const AppTool(
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    description: 'Convert PDF documents to HTML format',
    shortDescription: 'PDF to HTML',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.html,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['html'],
    instructions: [
      'Select a PDF file',
      'Tap Convert to HTML',
      'Wait for processing',
      'Download HTML file',
    ],
    features: [
      'Web-ready output',
      'Preserves formatting',
      'SEO friendly',
    ],
  ),
  const AppTool(
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to PDF files',
    shortDescription: 'Protect PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.lock,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select a PDF file',
      'Set password',
      'Tap Protect PDF',
      'Download protected file',
    ],
    features: [
      'Password encryption',
      'Permissions control',
      '128-bit security',
    ],
  ),
  const AppTool(
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages 90°, 180°, or 270°',
    shortDescription: 'Rotate PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.rotate_90_degrees_cw,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select a PDF file',
      'Choose rotation angle',
      'Select pages or all',
      'Download rotated PDF',
    ],
    features: [
      '90°, 180°, 270° rotation',
      'Single or all pages',
      'Batch processing',
    ],
  ),
  const AppTool(
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to PDF documents',
    shortDescription: 'Page Numbers',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.format_list_numbered,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select a PDF file',
      'Choose position and format',
      'Set starting number',
      'Download numbered PDF',
    ],
    features: [
      'Multiple positions',
      'Custom formatting',
      'Skip first page option',
    ],
  ),
  const AppTool(
    id: 'compare-pdf',
    name: 'Compare PDF',
    description: 'Compare two PDF files and find differences',
    shortDescription: 'Compare PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p0,
    icon: Icons.compare,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    supportsMultipleFiles: true,
    maxFilesCount: 2,
    instructions: [
      'Select two PDF files',
      'Tap Compare',
      'View differences',
      'Download comparison',
    ],
    features: [
      'Text comparison',
      'Visual differences',
      'Side-by-side view',
    ],
  ),

  // ==================== TEXT & CONTENT TOOLS (P0) ====================
  const AppTool(
    id: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to natural sounding speech',
    shortDescription: 'TTS',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.record_voice_over,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['audio'],
    instructions: [
      'Enter or paste text',
      'Select voice and language',
      'Tap Speak',
      'Play or download audio',
    ],
    features: [
      'Multiple languages',
      'Natural voices',
      'Adjust speed and pitch',
    ],
  ),
  const AppTool(
    id: 'speech-to-text',
    name: 'Speech to Text',
    description: 'Transcribe spoken words to text',
    shortDescription: 'Speech to Text',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.mic,
    supportedInputFormats: ['audio'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Tap microphone',
      'Start speaking',
      'View transcribed text',
      'Copy or save text',
    ],
    features: [
      'Real-time transcription',
      'Multiple languages',
      'Voice commands',
    ],
  ),
  const AppTool(
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong secure passwords',
    shortDescription: 'Password Gen',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.password,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Set password length',
      'Choose character types',
      'Generate password',
      'Copy to clipboard',
    ],
    features: [
      'Strong encryption',
      'Customizable length',
      'Character type options',
    ],
  ),
  const AppTool(
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Create various types of barcodes',
    shortDescription: 'Barcode Gen',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.barcode_reader,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['png', 'svg'],
    instructions: [
      'Select barcode type',
      'Enter data to encode',
      'Customize appearance',
      'Download barcode',
    ],
    features: [
      'UPC, EAN, Code128',
      'Customizable size',
      'High quality export',
    ],
  ),
  const AppTool(
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between different cases',
    shortDescription: 'Case Converter',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.text_fields,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter or paste text',
      'Select target case',
      'Convert instantly',
      'Copy result',
    ],
    features: [
      'UPPER, lower, Title Case',
      'camelCase, snake_case',
      'Sentence case',
    ],
  ),
  const AppTool(
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder text for designs',
    shortDescription: 'Lorem Ipsum',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.article,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Set number of paragraphs',
      'Choose word count',
      'Generate text',
      'Copy to clipboard',
    ],
    features: [
      'Custom length',
      'Multiple languages',
      'HTML tags option',
    ],
  ),
  const AppTool(
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and validate JSON data',
    shortDescription: 'JSON Formatter',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.data_object,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Paste JSON data',
      'Tap Format',
      'View formatted JSON',
      'Copy or download',
    ],
    features: [
      'Pretty print',
      'Syntax validation',
      'Minify option',
    ],
  ),
  const AppTool(
    id: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Encode and decode Base64 data',
    shortDescription: 'Base64',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p0,
    icon: Icons.code,
    supportedInputFormats: ['text', 'file'],
    supportedOutputFormats: ['text', 'file'],
    instructions: [
      'Enter text or upload file',
      'Choose encode or decode',
      'Process data',
      'Copy or download result',
    ],
    features: [
      'Text and file encoding',
      'URL safe Base64',
      'File to Base64',
    ],
  ),

  // ==================== P1 TOOLS (Future) ====================
  const AppTool(
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    shortDescription: 'XLSX to PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p1,
    icon: Icons.table_chart_outlined,
    supportedInputFormats: ['xlsx', 'xls'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select an Excel file',
      'Tap Convert to PDF',
      'Wait for processing',
      'Download PDF',
    ],
  ),
  const AppTool(
    id: 'pdf-to-xml',
    name: 'PDF to XML',
    description: 'Extract PDF data to XML format',
    shortDescription: 'PDF to XML',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p1,
    icon: Icons.code,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['xml'],
    instructions: [
      'Select a PDF',
      'Tap Convert to XML',
      'Wait for processing',
      'Download XML file',
    ],
  ),
  const AppTool(
    id: 'xml-to-pdf',
    name: 'XML to PDF',
    description: 'Convert XML data to PDF format',
    shortDescription: 'XML to PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p1,
    icon: Icons.code_off,
    supportedInputFormats: ['xml'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select an XML file',
      'Tap Convert to PDF',
      'Wait for processing',
      'Download PDF',
    ],
  ),
  const AppTool(
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted PDF files',
    shortDescription: 'Repair PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p1,
    icon: Icons.build,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select corrupted PDF',
      'Tap Repair PDF',
      'Wait for processing',
      'Download fixed PDF',
    ],
  ),
  const AppTool(
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password from protected PDFs',
    shortDescription: 'Unlock PDF',
    category: ToolCategory.pdfTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p1,
    icon: Icons.lock_open,
    supportedInputFormats: ['pdf'],
    supportedOutputFormats: ['pdf'],
    instructions: [
      'Select protected PDF',
      'Enter password if required',
      'Tap Unlock PDF',
      'Download unlocked PDF',
    ],
  ),
  const AppTool(
    id: 'image-ocr',
    name: 'Image to Text',
    description: 'Extract text from images using OCR',
    shortDescription: 'OCR',
    category: ToolCategory.imageTools,
    processingMode: ProcessingMode.api,
    priority: ToolPriority.p1,
    icon: Icons.text_fields,
    supportedInputFormats: ['jpg', 'jpeg', 'png', 'webp', 'pdf'],
    supportedOutputFormats: ['txt', 'docx'],
    instructions: [
      'Select an image with text',
      'Tap Extract Text',
      'Wait for OCR processing',
      'Copy or download text',
    ],
  ),
  const AppTool(
    id: 'word-counter',
    name: 'Word Count',
    description: 'Count words, characters, and sentences',
    shortDescription: 'Word Count',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p1,
    icon: Icons.format_list_numbered,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Paste or type your text',
      'View word count instantly',
      'See characters, sentences',
      'Copy statistics',
    ],
  ),
  const AppTool(
    id: 'hindi-word-counter',
    name: 'Hindi Word Count',
    description: 'Count words in Hindi text',
    shortDescription: 'Hindi Count',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p1,
    icon: Icons.translate,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Paste Hindi text',
      'View word count instantly',
      'See character count',
      'Copy statistics',
    ],
  ),
  const AppTool(
    id: 'typing-test',
    name: 'Typing Test',
    description: 'Test your typing speed and accuracy',
    shortDescription: 'Typing Test',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p2,
    icon: Icons.keyboard,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Start the test',
      'Type the displayed text',
      'See WPM and accuracy',
      'View results',
    ],
  ),
  const AppTool(
    id: 'youtube-tags',
    name: 'YouTube Tags',
    description: 'Generate SEO tags for YouTube videos',
    shortDescription: 'YT Tags',
    category: ToolCategory.otherTools,
    processingMode: ProcessingMode.local,
    priority: ToolPriority.p2,
    icon: Icons.smart_display,
    supportedInputFormats: ['text'],
    supportedOutputFormats: ['text'],
    instructions: [
      'Enter video topic',
      'Generate tag suggestions',
      'Copy tags to clipboard',
      'Use in YouTube',
    ],
  ),
];

// Get only P0 tools for MVP
List<AppTool> get p0Tools => allTools.where((tool) => tool.priority == ToolPriority.p0).toList();

// Get tools by category
List<AppTool> getToolsByCategory(ToolCategory category) {
  return p0Tools.where((tool) => tool.category == category).toList();
}

// Get tool by ID
AppTool? getToolById(String id) {
  try {
    return allTools.firstWhere((tool) => tool.id == id);
  } catch (e) {
    return null;
  }
}

// Search tools
List<AppTool> searchTools(String query) {
  final lowerQuery = query.toLowerCase();
  return p0Tools.where((tool) {
    return tool.name.toLowerCase().contains(lowerQuery) ||
        tool.description.toLowerCase().contains(lowerQuery) ||
        tool.shortDescription.toLowerCase().contains(lowerQuery);
  }).toList();
}
